# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_Files/NewInterview.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1024, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(2, 4, 1021, 491))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.nameOfResponderLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.nameOfResponderLabel.setFont(font)
        self.nameOfResponderLabel.setObjectName("nameOfResponderLabel")
        self.horizontalLayout.addWidget(self.nameOfResponderLabel)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.responderName = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.responderName.setFont(font)
        self.responderName.setObjectName("responderName")
        self.horizontalLayout.addWidget(self.responderName)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.companyNameLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.companyNameLabel.setFont(font)
        self.companyNameLabel.setObjectName("companyNameLabel")
        self.horizontalLayout_2.addWidget(self.companyNameLabel)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.companyName = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.companyName.setFont(font)
        self.companyName.setObjectName("companyName")
        self.horizontalLayout_2.addWidget(self.companyName)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.interviewerLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.interviewerLabel.setFont(font)
        self.interviewerLabel.setObjectName("interviewerLabel")
        self.horizontalLayout_3.addWidget(self.interviewerLabel)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.interviewerName = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.interviewerName.setFont(font)
        self.interviewerName.setObjectName("interviewerName")
        self.horizontalLayout_3.addWidget(self.interviewerName)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.wordSelectorLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.wordSelectorLabel.setFont(font)
        self.wordSelectorLabel.setObjectName("wordSelectorLabel")
        self.horizontalLayout_4.addWidget(self.wordSelectorLabel)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.wordsSelected20 = QtWidgets.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.wordsSelected20.setFont(font)
        self.wordsSelected20.setObjectName("wordsSelected20")
        self.horizontalLayout_4.addWidget(self.wordsSelected20)
        self.wordsSelected50 = QtWidgets.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.wordsSelected50.setFont(font)
        self.wordsSelected50.setChecked(True)
        self.wordsSelected50.setObjectName("wordsSelected50")
        self.horizontalLayout_4.addWidget(self.wordsSelected50)
        self.wordsSelected100 = QtWidgets.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.wordsSelected100.setFont(font)
        self.wordsSelected100.setObjectName("wordsSelected100")
        self.horizontalLayout_4.addWidget(self.wordsSelected100)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.dateLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.dateLabel.setFont(font)
        self.dateLabel.setObjectName("dateLabel")
        self.horizontalLayout_5.addWidget(self.dateLabel)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.dateEdited = QtWidgets.QDateEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.dateEdited.setFont(font)
        self.dateEdited.setDateTime(QtCore.QDateTime(QtCore.QDate(2021, 4, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdited.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(9717, 12, 31), QtCore.QTime(23, 59, 59)))
        self.dateEdited.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(1971, 9, 14), QtCore.QTime(0, 0, 0)))
        self.dateEdited.setCalendarPopup(True)
        self.dateEdited.setTimeSpec(QtCore.Qt.LocalTime)
        self.dateEdited.setObjectName("dateEdited")
        self.horizontalLayout_5.addWidget(self.dateEdited)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.enableEdit = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.enableEdit.setFont(font)
        self.enableEdit.setChecked(True)
        self.enableEdit.setObjectName("enableEdit")
        self.horizontalLayout_6.addWidget(self.enableEdit)
        self.submitDetails = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.submitDetails.setFont(font)
        self.submitDetails.setObjectName("submitDetails")
        self.horizontalLayout_6.addWidget(self.submitDetails)
        self.cancelInput = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.cancelInput.setFont(font)
        self.cancelInput.setObjectName("cancelInput")
        self.horizontalLayout_6.addWidget(self.cancelInput)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem7)
        self.horizontalLayout_7.addLayout(self.verticalLayout_2)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem8)

        self.retranslateUi(Form)
        self.enableEdit.clicked['bool'].connect(self.responderName.setEnabled)
        self.enableEdit.clicked['bool'].connect(self.companyName.setEnabled)
        self.enableEdit.clicked['bool'].connect(self.interviewerName.setEnabled)
        self.enableEdit.clicked['bool'].connect(self.wordsSelected20.setEnabled)
        self.enableEdit.clicked['bool'].connect(self.wordsSelected50.setEnabled)
        self.enableEdit.clicked['bool'].connect(self.wordsSelected100.setEnabled)
        self.enableEdit.clicked['bool'].connect(self.dateEdited.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "New Interview Form"))
        self.nameOfResponderLabel.setText(_translate("Form", "Name of Responder : "))
        self.companyNameLabel.setText(_translate("Form", "Company Name : "))
        self.interviewerLabel.setText(_translate("Form", "Interviewed By : "))
        self.wordSelectorLabel.setText(_translate("Form", "Number of Words : "))
        self.wordsSelected20.setText(_translate("Form", "20"))
        self.wordsSelected50.setText(_translate("Form", "50"))
        self.wordsSelected100.setText(_translate("Form", "100"))
        self.dateLabel.setText(_translate("Form", "Date : "))
        self.enableEdit.setText(_translate("Form", "Edit Interview Account Details"))
        self.submitDetails.setText(_translate("Form", "Submit"))
        self.cancelInput.setText(_translate("Form", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
