# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_Files/PredefinedWords.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1024, 450)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(3, 11, 1011, 431))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.wordToSearch = QtWidgets.QLineEdit(self.layoutWidget)
        self.wordToSearch.setObjectName("wordToSearch")
        self.horizontalLayout.addWidget(self.wordToSearch)
        self.searchPredefinedWord = QtWidgets.QPushButton(self.layoutWidget)
        self.searchPredefinedWord.setObjectName("searchPredefinedWord")
        self.horizontalLayout.addWidget(self.searchPredefinedWord)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.wordsSegment1 = QtWidgets.QScrollArea(self.layoutWidget)
        self.wordsSegment1.setWidgetResizable(True)
        self.wordsSegment1.setObjectName("wordsSegment1")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 84, 359))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.wordsSegment1.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.addWidget(self.wordsSegment1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.wordsSegment2 = QtWidgets.QScrollArea(self.layoutWidget)
        self.wordsSegment2.setWidgetResizable(True)
        self.wordsSegment2.setObjectName("wordsSegment2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 84, 359))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.wordsSegment2.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_2.addWidget(self.wordsSegment2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.wordsSegment3 = QtWidgets.QScrollArea(self.layoutWidget)
        self.wordsSegment3.setWidgetResizable(True)
        self.wordsSegment3.setObjectName("wordsSegment3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 85, 359))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.wordsSegment3.setWidget(self.scrollAreaWidgetContents_3)
        self.horizontalLayout_2.addWidget(self.wordsSegment3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.wordsSegment4 = QtWidgets.QScrollArea(self.layoutWidget)
        self.wordsSegment4.setWidgetResizable(True)
        self.wordsSegment4.setObjectName("wordsSegment4")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 84, 359))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.wordsSegment4.setWidget(self.scrollAreaWidgetContents_4)
        self.horizontalLayout_2.addWidget(self.wordsSegment4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.wordsSegment5 = QtWidgets.QScrollArea(self.layoutWidget)
        self.wordsSegment5.setWidgetResizable(True)
        self.wordsSegment5.setObjectName("wordsSegment5")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 84, 359))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.wordsSegment5.setWidget(self.scrollAreaWidgetContents_5)
        self.horizontalLayout_2.addWidget(self.wordsSegment5)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.serialNumberLabel = QtWidgets.QLabel(self.layoutWidget)
        self.serialNumberLabel.setObjectName("serialNumberLabel")
        self.horizontalLayout_3.addWidget(self.serialNumberLabel)
        self.updatedWordToCommit = QtWidgets.QLineEdit(self.layoutWidget)
        self.updatedWordToCommit.setObjectName("updatedWordToCommit")
        self.horizontalLayout_3.addWidget(self.updatedWordToCommit)
        self.wordToUpdate = QtWidgets.QPushButton(self.layoutWidget)
        self.wordToUpdate.setObjectName("wordToUpdate")
        self.horizontalLayout_3.addWidget(self.wordToUpdate)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "PredefinedWords"))
        self.searchPredefinedWord.setText(_translate("Form", "Search Word"))
        self.serialNumberLabel.setText(_translate("Form", "Serial No:     "))
        self.wordToUpdate.setText(_translate("Form", "Update"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
