# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_Files\GeneratedReport.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1024, 510)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(1024, 510))
        Form.setMaximumSize(QtCore.QSize(1280, 720))
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(3, 0, 1021, 501))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.generatedReport = QtWidgets.QTableWidget(self.layoutWidget)
        self.generatedReport.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generatedReport.sizePolicy().hasHeightForWidth())
        self.generatedReport.setSizePolicy(sizePolicy)
        self.generatedReport.setMinimumSize(QtCore.QSize(1019, 459))
        self.generatedReport.setMaximumSize(QtCore.QSize(1280, 680))
        self.generatedReport.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.generatedReport.setDragEnabled(True)
        self.generatedReport.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.generatedReport.setAlternatingRowColors(True)
        self.generatedReport.setShowGrid(True)
        self.generatedReport.setCornerButtonEnabled(False)
        self.generatedReport.setObjectName("generatedReport")
        self.generatedReport.setColumnCount(18)
        self.generatedReport.setRowCount(100)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(27, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(28, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(29, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(30, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(31, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(32, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(33, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(34, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(35, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(36, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(37, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(38, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(39, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(40, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(41, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(42, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(43, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(44, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(45, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(46, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(47, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(48, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(49, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(50, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(51, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(52, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(53, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(54, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(55, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(56, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(57, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(58, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(59, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(60, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(61, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(62, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(63, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(64, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(65, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(66, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(67, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(68, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(69, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(70, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(71, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(72, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(73, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(74, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(75, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(76, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(77, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(78, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(79, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(80, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(81, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(82, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(83, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(84, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(85, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(86, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(87, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(88, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(89, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(90, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(91, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(92, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(93, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(94, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(95, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(96, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(97, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(98, item)
        item = QtWidgets.QTableWidgetItem()
        self.generatedReport.setVerticalHeaderItem(99, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.generatedReport.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.generatedReport.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.generatedReport.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.generatedReport.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.generatedReport.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.generatedReport.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.generatedReport.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.generatedReport.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.generatedReport.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.generatedReport.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.generatedReport.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.generatedReport.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.generatedReport.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.generatedReport.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.generatedReport.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.generatedReport.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.generatedReport.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.generatedReport.setHorizontalHeaderItem(17, item)
        self.generatedReport.horizontalHeader().setVisible(True)
        self.generatedReport.horizontalHeader().setCascadingSectionResizes(False)
        self.generatedReport.horizontalHeader().setHighlightSections(False)
        self.generatedReport.horizontalHeader().setSortIndicatorShown(False)
        self.generatedReport.horizontalHeader().setStretchLastSection(False)
        self.generatedReport.verticalHeader().setVisible(True)
        self.generatedReport.verticalHeader().setHighlightSections(True)
        self.generatedReport.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.generatedReport)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.editGeneratedReport = QtWidgets.QCheckBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editGeneratedReport.sizePolicy().hasHeightForWidth())
        self.editGeneratedReport.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.editGeneratedReport.setFont(font)
        self.editGeneratedReport.setObjectName("editGeneratedReport")
        self.horizontalLayout.addWidget(self.editGeneratedReport)
        self.updateReport = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.updateReport.setFont(font)
        self.updateReport.setObjectName("updateReport")
        self.horizontalLayout.addWidget(self.updateReport)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        self.editGeneratedReport.clicked['bool'].connect(self.generatedReport.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "GeneratedReport"))
        item = self.generatedReport.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.generatedReport.verticalHeaderItem(1)
        item.setText(_translate("Form", "2"))
        item = self.generatedReport.verticalHeaderItem(2)
        item.setText(_translate("Form", "3"))
        item = self.generatedReport.verticalHeaderItem(3)
        item.setText(_translate("Form", "4"))
        item = self.generatedReport.verticalHeaderItem(4)
        item.setText(_translate("Form", "5"))
        item = self.generatedReport.verticalHeaderItem(5)
        item.setText(_translate("Form", "6"))
        item = self.generatedReport.verticalHeaderItem(6)
        item.setText(_translate("Form", "7"))
        item = self.generatedReport.verticalHeaderItem(7)
        item.setText(_translate("Form", "8"))
        item = self.generatedReport.verticalHeaderItem(8)
        item.setText(_translate("Form", "9"))
        item = self.generatedReport.verticalHeaderItem(9)
        item.setText(_translate("Form", "10"))
        item = self.generatedReport.verticalHeaderItem(10)
        item.setText(_translate("Form", "11"))
        item = self.generatedReport.verticalHeaderItem(11)
        item.setText(_translate("Form", "12"))
        item = self.generatedReport.verticalHeaderItem(12)
        item.setText(_translate("Form", "13"))
        item = self.generatedReport.verticalHeaderItem(13)
        item.setText(_translate("Form", "14"))
        item = self.generatedReport.verticalHeaderItem(14)
        item.setText(_translate("Form", "15"))
        item = self.generatedReport.verticalHeaderItem(15)
        item.setText(_translate("Form", "16"))
        item = self.generatedReport.verticalHeaderItem(16)
        item.setText(_translate("Form", "17"))
        item = self.generatedReport.verticalHeaderItem(17)
        item.setText(_translate("Form", "18"))
        item = self.generatedReport.verticalHeaderItem(18)
        item.setText(_translate("Form", "19"))
        item = self.generatedReport.verticalHeaderItem(19)
        item.setText(_translate("Form", "20"))
        item = self.generatedReport.verticalHeaderItem(20)
        item.setText(_translate("Form", "21"))
        item = self.generatedReport.verticalHeaderItem(21)
        item.setText(_translate("Form", "22"))
        item = self.generatedReport.verticalHeaderItem(22)
        item.setText(_translate("Form", "23"))
        item = self.generatedReport.verticalHeaderItem(23)
        item.setText(_translate("Form", "24"))
        item = self.generatedReport.verticalHeaderItem(24)
        item.setText(_translate("Form", "25"))
        item = self.generatedReport.verticalHeaderItem(25)
        item.setText(_translate("Form", "26"))
        item = self.generatedReport.verticalHeaderItem(26)
        item.setText(_translate("Form", "27"))
        item = self.generatedReport.verticalHeaderItem(27)
        item.setText(_translate("Form", "28"))
        item = self.generatedReport.verticalHeaderItem(28)
        item.setText(_translate("Form", "29"))
        item = self.generatedReport.verticalHeaderItem(29)
        item.setText(_translate("Form", "30"))
        item = self.generatedReport.verticalHeaderItem(30)
        item.setText(_translate("Form", "31"))
        item = self.generatedReport.verticalHeaderItem(31)
        item.setText(_translate("Form", "32"))
        item = self.generatedReport.verticalHeaderItem(32)
        item.setText(_translate("Form", "33"))
        item = self.generatedReport.verticalHeaderItem(33)
        item.setText(_translate("Form", "34"))
        item = self.generatedReport.verticalHeaderItem(34)
        item.setText(_translate("Form", "35"))
        item = self.generatedReport.verticalHeaderItem(35)
        item.setText(_translate("Form", "36"))
        item = self.generatedReport.verticalHeaderItem(36)
        item.setText(_translate("Form", "37"))
        item = self.generatedReport.verticalHeaderItem(37)
        item.setText(_translate("Form", "38"))
        item = self.generatedReport.verticalHeaderItem(38)
        item.setText(_translate("Form", "39"))
        item = self.generatedReport.verticalHeaderItem(39)
        item.setText(_translate("Form", "40"))
        item = self.generatedReport.verticalHeaderItem(40)
        item.setText(_translate("Form", "41"))
        item = self.generatedReport.verticalHeaderItem(41)
        item.setText(_translate("Form", "42"))
        item = self.generatedReport.verticalHeaderItem(42)
        item.setText(_translate("Form", "43"))
        item = self.generatedReport.verticalHeaderItem(43)
        item.setText(_translate("Form", "44"))
        item = self.generatedReport.verticalHeaderItem(44)
        item.setText(_translate("Form", "45"))
        item = self.generatedReport.verticalHeaderItem(45)
        item.setText(_translate("Form", "46"))
        item = self.generatedReport.verticalHeaderItem(46)
        item.setText(_translate("Form", "47"))
        item = self.generatedReport.verticalHeaderItem(47)
        item.setText(_translate("Form", "48"))
        item = self.generatedReport.verticalHeaderItem(48)
        item.setText(_translate("Form", "49"))
        item = self.generatedReport.verticalHeaderItem(49)
        item.setText(_translate("Form", "50"))
        item = self.generatedReport.verticalHeaderItem(50)
        item.setText(_translate("Form", "51"))
        item = self.generatedReport.verticalHeaderItem(51)
        item.setText(_translate("Form", "52"))
        item = self.generatedReport.verticalHeaderItem(52)
        item.setText(_translate("Form", "53"))
        item = self.generatedReport.verticalHeaderItem(53)
        item.setText(_translate("Form", "54"))
        item = self.generatedReport.verticalHeaderItem(54)
        item.setText(_translate("Form", "55"))
        item = self.generatedReport.verticalHeaderItem(55)
        item.setText(_translate("Form", "56"))
        item = self.generatedReport.verticalHeaderItem(56)
        item.setText(_translate("Form", "57"))
        item = self.generatedReport.verticalHeaderItem(57)
        item.setText(_translate("Form", "58"))
        item = self.generatedReport.verticalHeaderItem(58)
        item.setText(_translate("Form", "59"))
        item = self.generatedReport.verticalHeaderItem(59)
        item.setText(_translate("Form", "60"))
        item = self.generatedReport.verticalHeaderItem(60)
        item.setText(_translate("Form", "61"))
        item = self.generatedReport.verticalHeaderItem(61)
        item.setText(_translate("Form", "62"))
        item = self.generatedReport.verticalHeaderItem(62)
        item.setText(_translate("Form", "63"))
        item = self.generatedReport.verticalHeaderItem(63)
        item.setText(_translate("Form", "64"))
        item = self.generatedReport.verticalHeaderItem(64)
        item.setText(_translate("Form", "65"))
        item = self.generatedReport.verticalHeaderItem(65)
        item.setText(_translate("Form", "66"))
        item = self.generatedReport.verticalHeaderItem(66)
        item.setText(_translate("Form", "67"))
        item = self.generatedReport.verticalHeaderItem(67)
        item.setText(_translate("Form", "68"))
        item = self.generatedReport.verticalHeaderItem(68)
        item.setText(_translate("Form", "69"))
        item = self.generatedReport.verticalHeaderItem(69)
        item.setText(_translate("Form", "70"))
        item = self.generatedReport.verticalHeaderItem(70)
        item.setText(_translate("Form", "71"))
        item = self.generatedReport.verticalHeaderItem(71)
        item.setText(_translate("Form", "72"))
        item = self.generatedReport.verticalHeaderItem(72)
        item.setText(_translate("Form", "73"))
        item = self.generatedReport.verticalHeaderItem(73)
        item.setText(_translate("Form", "74"))
        item = self.generatedReport.verticalHeaderItem(74)
        item.setText(_translate("Form", "75"))
        item = self.generatedReport.verticalHeaderItem(75)
        item.setText(_translate("Form", "76"))
        item = self.generatedReport.verticalHeaderItem(76)
        item.setText(_translate("Form", "77"))
        item = self.generatedReport.verticalHeaderItem(77)
        item.setText(_translate("Form", "78"))
        item = self.generatedReport.verticalHeaderItem(78)
        item.setText(_translate("Form", "79"))
        item = self.generatedReport.verticalHeaderItem(79)
        item.setText(_translate("Form", "80"))
        item = self.generatedReport.verticalHeaderItem(80)
        item.setText(_translate("Form", "81"))
        item = self.generatedReport.verticalHeaderItem(81)
        item.setText(_translate("Form", "82"))
        item = self.generatedReport.verticalHeaderItem(82)
        item.setText(_translate("Form", "83"))
        item = self.generatedReport.verticalHeaderItem(83)
        item.setText(_translate("Form", "84"))
        item = self.generatedReport.verticalHeaderItem(84)
        item.setText(_translate("Form", "85"))
        item = self.generatedReport.verticalHeaderItem(85)
        item.setText(_translate("Form", "86"))
        item = self.generatedReport.verticalHeaderItem(86)
        item.setText(_translate("Form", "87"))
        item = self.generatedReport.verticalHeaderItem(87)
        item.setText(_translate("Form", "88"))
        item = self.generatedReport.verticalHeaderItem(88)
        item.setText(_translate("Form", "89"))
        item = self.generatedReport.verticalHeaderItem(89)
        item.setText(_translate("Form", "90"))
        item = self.generatedReport.verticalHeaderItem(90)
        item.setText(_translate("Form", "91"))
        item = self.generatedReport.verticalHeaderItem(91)
        item.setText(_translate("Form", "92"))
        item = self.generatedReport.verticalHeaderItem(92)
        item.setText(_translate("Form", "93"))
        item = self.generatedReport.verticalHeaderItem(93)
        item.setText(_translate("Form", "94"))
        item = self.generatedReport.verticalHeaderItem(94)
        item.setText(_translate("Form", "95"))
        item = self.generatedReport.verticalHeaderItem(95)
        item.setText(_translate("Form", "96"))
        item = self.generatedReport.verticalHeaderItem(96)
        item.setText(_translate("Form", "97"))
        item = self.generatedReport.verticalHeaderItem(97)
        item.setText(_translate("Form", "98"))
        item = self.generatedReport.verticalHeaderItem(98)
        item.setText(_translate("Form", "99"))
        item = self.generatedReport.verticalHeaderItem(99)
        item.setText(_translate("Form", "100"))
        item = self.generatedReport.horizontalHeaderItem(0)
        item.setText(_translate("Form", "S Word"))
        item = self.generatedReport.horizontalHeaderItem(1)
        item.setText(_translate("Form", "RT( 5ths )"))
        item = self.generatedReport.horizontalHeaderItem(2)
        item.setText(_translate("Form", "RT( Sec )"))
        item = self.generatedReport.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Reaction"))
        item = self.generatedReport.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Reproduced"))
        item = self.generatedReport.horizontalHeaderItem(8)
        item.setText(_translate("Form", "COMP"))
        item = self.generatedReport.horizontalHeaderItem(9)
        item.setText(_translate("Form", "LEX         "))
        item = self.generatedReport.horizontalHeaderItem(10)
        item.setText(_translate("Form", "INDIC"))
        item = self.generatedReport.horizontalHeaderItem(11)
        item.setText(_translate("Form", "ATORS    "))
        item = self.generatedReport.horizontalHeaderItem(15)
        item.setText(_translate("Form", "Total"))
        item = self.generatedReport.horizontalHeaderItem(16)
        item.setText(_translate("Form", "Factual"))
        item = self.generatedReport.horizontalHeaderItem(17)
        item.setText(_translate("Form", "Ego-centric"))
        self.editGeneratedReport.setText(_translate("Form", "Edit Report"))
        self.updateReport.setText(_translate("Form", "Update Report"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
